changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/kabipay_dev
username=${KABIPAY_DB_USER}
password=${KABIPAY_DB_PASSWORD}
defaultSchemaName=kabipay_ops
# Liquibase history table must live in an existing schema; kabipay_ops is created by migration 0000-001.
liquibaseSchemaName=public
driver=org.postgresql.Driver
logLevel=INFO
