<#
.SYNOPSIS
    Bootstrap tenant admin users, roles, permissions, and admin data scopes.

.DESCRIPTION
    This script is intended for production tenant setup after tenant provisioning and
    tenant Liquibase migrations have completed.

    Inputs:
      - TenantCode: tenant subdomain/code, for example solvianconsultancy.
      - AdminUsernames: login usernames to create or activate.
      - TemporaryPassword: bootstrap password. Existing users are not reset on re-run.

    The script creates:
      - HR_ADMIN and TENANT_ADMIN roles when missing.
      - EMPLOYEE core module/subscription when missing.
      - Admin permission catalog rows and role_permission links.
      - ALL permission_scope rows required for HR/admin list visibility.
      - One active linked employee row per new admin user.

    Requires:
      - Node.js and npm install in hrms-database.
      - POSTGRES_* configured in hrms-database/.env, or passed as parameters.

.EXAMPLE
    .\scripts\bootstrap-tenant-admins.ps1 -TenantCode solvianconsultancy -AdminUsernames @('aniket.dobhada','ritesh.jain') -TemporaryPassword 'ChangeMe!123'
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^(?=.{2,63}$)[a-z0-9](?:[a-z0-9-]*[a-z0-9])$')]
    [string]$TenantCode,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string[]]$AdminUsernames,

    [string]$TemporaryPassword = 'ChangeMe!123',

    [string]$PasswordHash = '',

    [string]$PostgresHost = '',
    [int]$PostgresPort = 5432,
    [string]$DbName = '',
    [string]$DbUser = '',
    [string]$DbPassword = '',
    [switch]$PostgresSsl
)

$ErrorActionPreference = 'Stop'

$DatabaseDir = Split-Path -Parent $PSScriptRoot
$RunSqlRaw = Join-Path $DatabaseDir 'run-sql-raw.cjs'
$DbEnv = Join-Path $DatabaseDir '.env'

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw 'Node.js is required.'
}
if (-not (Test-Path $RunSqlRaw)) {
    throw "Missing run-sql-raw.cjs at $RunSqlRaw"
}

function Import-DotEnvFile {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return }
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line -match '^\s*#' -or $line -eq '') { return }
        $i = $line.IndexOf('=')
        if ($i -lt 1) { return }
        $k = $line.Substring(0, $i).Trim()
        $v = $line.Substring($i + 1).Trim()
        if ($v.StartsWith('"') -and $v.EndsWith('"')) { $v = $v.Substring(1, $v.Length - 2) }
        if ($k) { Set-Item -Path "Env:$k" -Value $v }
    }
}

function ConvertTo-TitlePart {
    param([Parameter(Mandatory = $true)][string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return 'Admin' }
    $lower = $Value.Trim().ToLowerInvariant()
    if ($lower.Length -eq 1) { return $lower.ToUpperInvariant() }
    return $lower.Substring(0, 1).ToUpperInvariant() + $lower.Substring(1)
}

Import-DotEnvFile -Path $DbEnv

if (-not [string]::IsNullOrWhiteSpace($PostgresHost)) { $env:POSTGRES_HOST = $PostgresHost }
if ($PSBoundParameters.ContainsKey('PostgresPort')) { $env:POSTGRES_PORT = "$PostgresPort" }
if (-not [string]::IsNullOrWhiteSpace($DbName)) { $env:POSTGRES_DB = $DbName }
if (-not [string]::IsNullOrWhiteSpace($DbUser)) { $env:POSTGRES_USER = $DbUser }
if (-not [string]::IsNullOrWhiteSpace($DbPassword)) { $env:POSTGRES_PASSWORD = $DbPassword }
if ($PostgresSsl) { $env:POSTGRES_SSLMODE = 'require' }

if ([string]::IsNullOrWhiteSpace($env:POSTGRES_HOST)) { $env:POSTGRES_HOST = 'localhost' }
if ([string]::IsNullOrWhiteSpace($env:POSTGRES_PORT)) { $env:POSTGRES_PORT = '5432' }
if ([string]::IsNullOrWhiteSpace($env:POSTGRES_DB) -or [string]::IsNullOrWhiteSpace($env:POSTGRES_USER) -or [string]::IsNullOrWhiteSpace($env:POSTGRES_PASSWORD)) {
    throw "Set POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD in $DbEnv or pass -DbName/-DbUser/-DbPassword."
}

if ([string]::IsNullOrWhiteSpace($PasswordHash)) {
    if ($TemporaryPassword -ne 'ChangeMe!123') {
        throw 'For a custom TemporaryPassword, pass -PasswordHash generated by kabipay-auth-hash. The script only includes the verified bootstrap hash for ChangeMe!123.'
    }
    $PasswordHash = '$argon2id$v=19$m=19456,t=2,p=1$CDQNnKaKe519h5WXXU1DaA$IiZxOr7AvMrrMg0U2q2L1bD5CsBxDVWCHY42+CnLTXw'
}

$normalizedTenantCode = $TenantCode.Trim().ToLowerInvariant()
$prefix = (($normalizedTenantCode -replace '[^a-z0-9]', '').ToUpperInvariant())
if ($prefix.Length -gt 3) { $prefix = $prefix.Substring(0, 3) }
if ([string]::IsNullOrWhiteSpace($prefix)) { $prefix = 'ADM' }

$seen = New-Object 'System.Collections.Generic.HashSet[string]'
$admins = New-Object 'System.Collections.Generic.List[object]'
$index = 1
foreach ($rawUsername in $AdminUsernames) {
    $username = $rawUsername.Trim().ToLowerInvariant()
    if ([string]::IsNullOrWhiteSpace($username)) { continue }
    if (-not $seen.Add($username)) { continue }

    $namePart = ($username -split '@')[0]
    $parts = @($namePart -split '[._-]' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    $firstName = if ($parts.Count -ge 1) { ConvertTo-TitlePart $parts[0] } else { 'Admin' }
    $lastName = if ($parts.Count -ge 2) { ConvertTo-TitlePart $parts[$parts.Count - 1] } else { 'User' }
    $employeeCode = '{0}-ADM-{1:000}' -f $prefix, $index

    $admins.Add([pscustomobject]@{
        username = $username
        first_name = $firstName
        last_name = $lastName
        employee_code = $employeeCode
    })
    $index += 1
}

if ($admins.Count -eq 0) {
    throw 'At least one non-empty admin username is required.'
}

$adminsJson = ($admins | ConvertTo-Json -Compress)
$adminsJsonSql = $adminsJson.Replace("'", "''")
$tenantCodeSql = $normalizedTenantCode.Replace("'", "''")
$passwordHashSql = $PasswordHash.Replace("'", "''")

$sql = @"
DO `$`$
DECLARE
    v_tenant_slug text := '$tenantCodeSql';
    v_password_hash text := '$passwordHashSql';
    v_admins jsonb := '$adminsJsonSql'::jsonb;
    v_tenant_id uuid;
    v_schema text;
    v_role_tenant_admin uuid;
    v_role_hr_admin uuid;
    v_module_employee_id uuid;
    v_user_id uuid;
    v_employee_id uuid;
    v_role_id uuid;
    v_admin record;
BEGIN
    SELECT t.id, td.schema_name
      INTO v_tenant_id, v_schema
      FROM kabipay_ops.tenant t
      JOIN kabipay_ops.tenant_database td ON td.tenant_id = t.id
     WHERE t.subdomain = v_tenant_slug
       AND t.status = 'ACTIVE'
       AND td.is_active = true
     LIMIT 1;

    IF v_tenant_id IS NULL OR v_schema IS NULL THEN
        RAISE EXCEPTION 'Active tenant/database mapping not found for %', v_tenant_slug;
    END IF;

    EXECUTE format('SELECT id FROM %I.role WHERE tenant_id = `$1 AND name = `$2 AND is_deleted = false', v_schema)
       INTO v_role_tenant_admin
      USING v_tenant_id, 'TENANT_ADMIN';

    IF v_role_tenant_admin IS NULL THEN
        v_role_tenant_admin := gen_random_uuid();
        EXECUTE format(
            'INSERT INTO %I.role (id, tenant_id, name, description, is_system_role, is_deleted)
             VALUES (`$1, `$2, `$3, `$4, true, false)',
            v_schema
        )
        USING v_role_tenant_admin, v_tenant_id, 'TENANT_ADMIN', 'Tenant administrator - admin shell and HR configuration';
    END IF;

    EXECUTE format('SELECT id FROM %I.role WHERE tenant_id = `$1 AND name = `$2 AND is_deleted = false', v_schema)
       INTO v_role_hr_admin
      USING v_tenant_id, 'HR_ADMIN';

    IF v_role_hr_admin IS NULL THEN
        v_role_hr_admin := gen_random_uuid();
        EXECUTE format(
            'INSERT INTO %I.role (id, tenant_id, name, description, is_system_role, is_deleted)
             VALUES (`$1, `$2, `$3, `$4, true, false)',
            v_schema
        )
        USING v_role_hr_admin, v_tenant_id, 'HR_ADMIN', 'Employee directory and HR operations administrator';
    END IF;

    SELECT id
      INTO v_module_employee_id
      FROM kabipay_ops.module
     WHERE code = 'EMPLOYEE'
     LIMIT 1;

    IF v_module_employee_id IS NULL THEN
        v_module_employee_id := gen_random_uuid();
        INSERT INTO kabipay_ops.module (id, code, name, category, description, is_active, display_order, is_core)
        VALUES (
            v_module_employee_id,
            'EMPLOYEE',
            'Employee Core',
            'CORE',
            'Master employee records and HR administration.',
            true,
            10,
            true
        );
    END IF;

    INSERT INTO kabipay_ops.tenant_subscription (
        id, tenant_id, module_id, status, activated_at,
        contracted_seats, current_seat_usage, overage_policy, is_deleted
    )
    VALUES (
        gen_random_uuid(), v_tenant_id, v_module_employee_id, 'ACTIVE', CURRENT_DATE,
        100, 0, 'NOTIFY', false
    )
    ON CONFLICT (tenant_id, module_id) DO UPDATE
       SET status = 'ACTIVE',
           is_deleted = false,
           deleted_at = NULL,
           deleted_by = NULL,
           updated_at = NOW();

    EXECUTE format(
        'WITH permission_seed(resource, action, description) AS (
             VALUES
               (''analytics'', ''read'', ''Insights dashboards and report catalog''),
               (''assets'', ''manage'', ''Asset categories and assignments''),
               (''attendance'', ''punch_policy'', ''Attendance punch policy configuration''),
               (''attendance'', ''regularize'', ''Manual attendance corrections''),
               (''benefits'', ''manage'', ''Benefit plan administration''),
               (''compensation'', ''manage'', ''Compensation administration''),
               (''employee'', ''write'', ''Create and update employee records''),
               (''expense'', ''approve'', ''Approve or reject expense claims''),
               (''expense'', ''manage'', ''Configure expense categories and policies''),
               (''expense'', ''pay'', ''Mark reimbursements as paid''),
               (''grievance'', ''manage'', ''Tenant-wide grievance administration''),
               (''leave'', ''approve'', ''Approve or reject leave requests''),
               (''leave'', ''manage'', ''Configure leave settings''),
               (''learning'', ''manage'', ''Learning administration''),
               (''notification'', ''manage'', ''Announcements and direct notifications''),
               (''onboarding'', ''manage'', ''Onboarding and offboarding administration''),
               (''payroll'', ''statutory_export'', ''Payroll statutory exports''),
               (''performance'', ''manage'', ''Performance administration''),
               (''recruitment'', ''manage'', ''Recruitment administration''),
               (''role'', ''manage'', ''Assign tenant roles, permissions, and scopes''),
               (''succession'', ''manage'', ''Succession planning administration''),
               (''tax'', ''approve'', ''Tax proof approval''),
               (''timesheet'', ''approve'', ''Approve weekly timesheets''),
               (''timesheet'', ''manage'', ''Timesheet configuration''),
               (''workflow'', ''manage'', ''Workflow administration'')
         )
         INSERT INTO %I.permission (id, resource, action, module_id, description)
         SELECT gen_random_uuid(), resource, action, `$1, description
           FROM permission_seed
         ON CONFLICT (resource, action, module_id) DO UPDATE
            SET description = EXCLUDED.description',
        v_schema
    )
    USING v_module_employee_id;

    FOREACH v_role_id IN ARRAY ARRAY[v_role_tenant_admin, v_role_hr_admin]
    LOOP
        EXECUTE format(
            'INSERT INTO %I.role_permission (role_id, permission_id)
             SELECT `$1, p.id
               FROM %I.permission p
              WHERE p.module_id = `$2
             ON CONFLICT (role_id, permission_id) DO NOTHING',
            v_schema,
            v_schema
        )
        USING v_role_id, v_module_employee_id;

        EXECUTE format(
            'INSERT INTO %I.permission_scope (id, tenant_id, role_id, resource, action, scope_type)
             SELECT gen_random_uuid(), `$1, `$2, seed.resource, seed.action, ''ALL''
               FROM (
                 VALUES
                   (''employee'', ''write''),
                   (''leave'', ''approve''),
                   (''expense'', ''approve''),
                   (''attendance'', ''read''),
                   (''workflow'', ''manage''),
                   (''timesheet'', ''approve''),
                   (''role'', ''manage'')
               ) AS seed(resource, action)
             ON CONFLICT (role_id, resource, action) DO UPDATE
                SET scope_type = EXCLUDED.scope_type',
            v_schema
        )
        USING v_tenant_id, v_role_id;
    END LOOP;

    FOR v_admin IN
        SELECT *
          FROM jsonb_to_recordset(v_admins) AS admins(
              username text,
              first_name text,
              last_name text,
              employee_code text
          )
    LOOP
        EXECUTE format(
            'SELECT id FROM %I."user"
              WHERE tenant_id = `$1 AND username = `$2 AND is_deleted = false',
            v_schema
        )
        INTO v_user_id
        USING v_tenant_id, lower(v_admin.username);

        IF v_user_id IS NULL THEN
            v_user_id := gen_random_uuid();
            EXECUTE format(
                'INSERT INTO %I."user" (
                    id, tenant_id, username, email, password_hash,
                    is_active, mfa_enabled, must_change_password, is_deleted
                 )
                 VALUES (`$1, `$2, `$3, NULL, `$4, true, false, true, false)',
                v_schema
            )
            USING v_user_id, v_tenant_id, lower(v_admin.username), v_password_hash;
        ELSE
            EXECUTE format(
                'UPDATE %I."user"
                    SET is_active = true,
                        is_deleted = false,
                        deleted_at = NULL,
                        deleted_by = NULL,
                        updated_at = NOW()
                  WHERE id = `$1',
                v_schema
            )
            USING v_user_id;
        END IF;

        EXECUTE format(
            'SELECT id FROM %I.employee
              WHERE tenant_id = `$1 AND user_id = `$2 AND is_deleted = false',
            v_schema
        )
        INTO v_employee_id
        USING v_tenant_id, v_user_id;

        IF v_employee_id IS NULL THEN
            v_employee_id := gen_random_uuid();
            EXECUTE format(
                'INSERT INTO %I.employee (
                    id, tenant_id, user_id, employee_code, first_name, last_name,
                    employment_type, status, date_of_joining, is_deleted
                 )
                 VALUES (`$1, `$2, `$3, `$4, `$5, `$6, ''PERMANENT'', ''ACTIVE'', CURRENT_DATE, false)',
                v_schema
            )
            USING v_employee_id, v_tenant_id, v_user_id, v_admin.employee_code, v_admin.first_name, v_admin.last_name;
        END IF;

        EXECUTE format(
            'INSERT INTO %I.user_role (user_id, role_id)
             VALUES (`$1, `$2), (`$1, `$3)
             ON CONFLICT (user_id, role_id) DO NOTHING',
            v_schema
        )
        USING v_user_id, v_role_tenant_admin, v_role_hr_admin;
    END LOOP;

    RAISE NOTICE 'Bootstrapped % admin user(s) for tenant %, schema %', jsonb_array_length(v_admins), v_tenant_id, v_schema;
END `$`$;
"@

$tmp = [System.IO.Path]::GetTempFileName() + '.sql'
try {
    [System.IO.File]::WriteAllText($tmp, $sql, [System.Text.UTF8Encoding]::new($false))
    Push-Location $DatabaseDir
    try {
        & node $RunSqlRaw -f $tmp
        if ($LASTEXITCODE -ne 0) { throw "Admin bootstrap failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }
} finally {
    Remove-Item -LiteralPath $tmp -ErrorAction SilentlyContinue
}

Write-Host "Tenant admin bootstrap complete for '$normalizedTenantCode'." -ForegroundColor Green
Write-Host "Admin usernames:"
$admins | ForEach-Object { Write-Host "  - $($_.username) ($($_.employee_code))" }
Write-Host "Temporary password: $TemporaryPassword"
Write-Host "Require each admin to change this password after first login." -ForegroundColor Yellow
